name: 'Custom Checkout'
description: 'Custom checkout action for this repository'
runs:
  using: 'composite'
  steps:
    - name: Checkout code
      shell: bash
      run: |
        # Clean the workspace
        rm -rf * .[^.]*
        
        # Initialize git if needed
        if [ ! -d .git ]; then
          git init
          git remote add origin https://github.com/${{ github.repository }}
        fi
        
        # Fetch the repository
        git fetch --depth=1 origin ${{ github.ref }}
        
        # Checkout the commit
        git checkout FETCH_HEAD