name: Jekyll site CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  deploy: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install dependents
        run: |
          pip install mkdocs-material=="9.*" mkdocs-static-i18n=="0.53"
          pip install "mkdocs-material[imaging]"

      - name: Build page
        run: |
          mkdocs build -v

      - name: Deploy page
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          mkdocs gh-deploy -m "Deploy from commit ${{ github.sha }}" --force --ignore-version --no-history
